### ISSUE TITLE
Check that OAuth2 tokens have the MEASUREMENT.CREATE scope

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/RADAR-Gateway#11]
Only OAuth 2.0 tokens that have the Management Portal `MEASUREMENT.CREATE` scope should be allowed to add measurements. @dennyverbeeck is that correct?

**Comment by dennyverbeeck** [comment]
Exactly. Probably the [`RadarAuthorization.checkPermissionOnProject()`](https://radar-cns.github.io/ManagementPortal/ra-javadoc/org/radarcns/auth/authorization/RadarAuthorization.html#checkPermissionOnProject-com.auth0.jwt.interfaces.DecodedJWT-org.radarcns.auth.authorization.Permission-java.lang.String-) method from `radar-auth` is the one you want to use in this case.

**Comment by blootsvoets** [comment]
OK, great. Would the `authorities` JWT property not be redundant then? I get
```json
"roles": [
  "radar-test:ROLE_PARTICIPANT"
],
"authorities": [
  "ROLE_PARTICIPANT"
],
```

**Comment by dennyverbeeck** [comment]
Currently the only case where it is not redundant is for the `SYS_ADMIN` authority, since it does not belong to a project, and thus it is not a role. I also think the MP frontend uses this JWT property, to change the UI based on the authority (e.g. admin menu only shows up for admins). It might indeed be worth refactoring that sometime in the future to reduce the redundancies.
